Update ipfs: add web3storage, switch to cidv1, fix pinata
stakewise/sw-utils pull request #22
Opened 2023-01-31 15:14 UTC by cyc60

2023-01-31 16:08 UTC, evgeny-stakewise commented on sw_utils/ipfs.py
> +        headers['Content-Type'] = 'application/json'
The same issue about `self.headers`

2023-01-31 16:30 UTC, evgeny-stakewise requested changes
OK in general

2023-02-01 07:08 UTC, evgeny-stakewise approved these changes

2023-02-01 09:06 UTC, tsudmi approved these changes

2023-02-06 06:53 UTC, merged